import React, { useState, useEffect } from "react";
import { PRIORITY_SECTORS_HI, PRIORITY_SECTORS_EN, PrioritySector, ActionStep } from "./data";
import { Header } from "./components/Header";
import { PriorityList } from "./components/PriorityList";
import { ActiveSectorView } from "./components/ActiveSectorView";
import { OverviewReport } from "./components/OverviewReport";
import { NotificationHistoryView } from "./components/NotificationHistoryView";
import { Login, UserCredentials } from "./components/Login";
import { 
  Building2, Award, Landmark, CheckSquare, Sparkles, Scale, Info, 
  HelpCircle, ChevronRight, FileText, CheckCircle
} from "lucide-react";
import { getSupabaseClient } from "./lib/supabase";
import { useLanguage } from "./contexts/LanguageContext";

export default function App() {
  const { language } = useLanguage();
  const [loggedInUser, setLoggedInUser] = useState<UserCredentials | null>(null);
  
  // Global Sector state (restored from localStorage if possible)
  const [sectors, setSectors] = useState<PrioritySector[]>([]);
  const [activeSectorId, setActiveSectorId] = useState<number>(1);
  const [viewMode, setViewMode] = useState<"dashboard" | "report">("dashboard");
  
  // Storage of all custom AI strategies generated by Gemini
  const [generatedStrategies, setGeneratedStrategies] = useState<{ [key: string]: string }>({});

  const [isSupabaseConnected, setIsSupabaseConnected] = useState(false);

  // Apply localized data when language changes, preserving completion status
  useEffect(() => {
    const localizedData = language === 'en' ? PRIORITY_SECTORS_EN : PRIORITY_SECTORS_HI;
    
    setSectors(prevSectors => {
      if (prevSectors.length === 0) return prevSectors; // Will be initialized by the mount effect
      
      return localizedData.map(newSec => {
        const oldSec = prevSectors.find(s => s.id === newSec.id);
        if (!oldSec) return newSec;
        
        const mergedActions = newSec.defaultActions.map(newAct => {
          const oldAct = oldSec.defaultActions.find(a => a.id === newAct.id);
          return oldAct ? { ...newAct, completed: oldAct.completed } : newAct;
        });
        
        const customActions = oldSec.defaultActions.filter(a => a.isCustom);
        
        return {
          ...newSec,
          defaultActions: [...mergedActions, ...customActions]
        };
      });
    });
  }, [language]);

  // Initialize and load state
  useEffect(() => {
    const localizedData = language === 'en' ? PRIORITY_SECTORS_EN : PRIORITY_SECTORS_HI;
    const savedUser = localStorage.getItem("police_planner_user");
    if (savedUser) {
      try { setLoggedInUser(JSON.parse(savedUser)); } catch (e) {}
    }
    const savedSectors = localStorage.getItem("police_planner_sectors");
    const savedStrategies = localStorage.getItem("police_planner_strategies");

    if (savedSectors) {
      try {
        const parsedSectors = JSON.parse(savedSectors) as PrioritySector[];
        // Map parsed sectors to current language data but preserve completed status
        const mergedSectors = localizedData.map(newSec => {
          const oldSec = parsedSectors.find(s => s.id === newSec.id);
          if (!oldSec) return newSec;
          
          const mergedActions = newSec.defaultActions.map(newAct => {
            const oldAct = oldSec.defaultActions.find(a => a.id === newAct.id);
            return oldAct ? { ...newAct, completed: oldAct.completed } : newAct;
          });
          
          const customActions = oldSec.defaultActions.filter(a => a.isCustom);
          
          return {
            ...newSec,
            defaultActions: [...mergedActions, ...customActions]
          };
        });
        setSectors(mergedSectors);
      } catch (e) {
        setSectors(localizedData);
      }
    } else {
      setSectors(localizedData);
    }

    if (savedStrategies) {
      try {
        setGeneratedStrategies(JSON.parse(savedStrategies));
      } catch (e) {
        setGeneratedStrategies({});
      }
    }

    // Check if Supabase client config exists
    const client = getSupabaseClient();
    setIsSupabaseConnected(!!client);
  }, []);

  // Fetch data from Supabase if connected
  const loadDataFromSupabase = async () => {
    const client = getSupabaseClient();
    if (!client) return;

    try {
      // 1. Fetch sectors checklist state
      const { data: dbSectors, error: sectorsError } = await client
        .from("sectors_state")
        .select("*");

      if (!sectorsError && dbSectors && dbSectors.length > 0) {
        setSectors(prev => {
          return prev.map(sec => {
            const matched = dbSectors.find((d: any) => d.sector_id === sec.id);
            if (matched) {
              return {
                ...sec,
                defaultActions: matched.default_actions
              };
            }
            return sec;
          });
        });
      }

      // 2. Fetch AI strategies
      const { data: dbStrategies, error: strategiesError } = await client
        .from("ai_strategies")
        .select("*");

      if (!strategiesError && dbStrategies && dbStrategies.length > 0) {
        const mapped: { [key: string]: string } = {};
        dbStrategies.forEach((item: any) => {
          mapped[item.strategy_key] = item.content;
        });
        setGeneratedStrategies(prev => ({
          ...prev,
          ...mapped
        }));
      }
    } catch (err) {
      console.error("Supabase sync fetch error:", err);
    }
  };

  useEffect(() => {
    if (isSupabaseConnected) {
      loadDataFromSupabase();
    }
  }, [isSupabaseConnected]);

  // Save changes to localStorage & Supabase
  const saveSectorsState = async (updatedSectors: PrioritySector[]) => {
    setSectors(updatedSectors);
    localStorage.setItem("police_planner_sectors", JSON.stringify(updatedSectors));

    const client = getSupabaseClient();
    if (client) {
      try {
        for (const sec of updatedSectors) {
          await client
            .from("sectors_state")
            .upsert({
              sector_id: sec.id,
              default_actions: sec.defaultActions,
              updated_at: new Date().toISOString()
            }, { onConflict: "sector_id" });
        }
      } catch (err) {
        console.error("Supabase save error:", err);
      }
    }
  };

  // Toggle SOP Action task status
  const handleToggleAction = (sectorId: number, actionId: string) => {
    const updated = sectors.map((sec) => {
      if (sec.id === sectorId) {
        return {
          ...sec,
          defaultActions: sec.defaultActions.map((act) => {
            if (act.id === actionId) {
              return { ...act, completed: !act.completed };
            }
            return act;
          })
        };
      }
      return sec;
    });

    saveSectorsState(updated);
  };

  // Append new custom actions to checklists
  const handleAddCustomAction = (
    sectorId: number,
    title: string,
    description: string,
    timeline: string,
    owner: string,
    ownerPhone?: string,
    ownerEmail?: string
  ) => {
    const newAction: ActionStep = {
      id: `${sectorId}_custom_${Date.now()}`,
      title,
      description,
      timeline,
      owner,
      ownerPhone,
      ownerEmail,
      completed: false,
      isCustom: true
    };

    const updated = sectors.map((sec) => {
      if (sec.id === sectorId) {
        return {
          ...sec,
          defaultActions: [...sec.defaultActions, newAction]
        };
      }
      return sec;
    });

    saveSectorsState(updated);
  };

  // Delete an action from checklist (custom or default)
  const handleDeleteAction = (sectorId: number, actionId: string) => {
    const updated = sectors.map((sec) => {
      if (sec.id === sectorId) {
        return {
          ...sec,
          defaultActions: sec.defaultActions.filter((act) => act.id !== actionId)
        };
      }
      return sec;
    });

    saveSectorsState(updated);
  };

  // Edit fields of an existing action element
  const handleEditAction = (sectorId: number, actionId: string, updatedFields: Partial<ActionStep>) => {
    const updated = sectors.map((sec) => {
      if (sec.id === sectorId) {
        return {
          ...sec,
          defaultActions: sec.defaultActions.map((act) => {
            if (act.id === actionId) {
              return { ...act, ...updatedFields };
            }
            return act;
          })
        };
      }
      return sec;
    });

    saveSectorsState(updated);
  };

  // Save generated strategy
  const handleSaveStrategy = async (sectorId: number, scenarioKey: string, text: string) => {
    const updated = {
      ...generatedStrategies,
      [scenarioKey]: text
    };
    setGeneratedStrategies(updated);
    localStorage.setItem("police_planner_strategies", JSON.stringify(updated));

    const client = getSupabaseClient();
    if (client) {
      try {
        await client
          .from("ai_strategies")
          .upsert({
            strategy_key: scenarioKey,
            content: text,
            updated_at: new Date().toISOString()
          }, { onConflict: "strategy_key" });
      } catch (err) {
        console.error("Supabase strategy sync error:", err);
      }
    }
  };

  // Reset entire application to official defaults
  const handleResetAll = async () => {
    const confirmMsg = language === 'en' 
      ? "Are you sure you want to reset all customizations, sub-tasks, and generated AI strategies to return to government standards?"
      : "क्या आप वाकई सभी कस्टमाइजेशन, सब-टास्क और जनरेट की गई AI रणनीतियों को रीसेट कर सरकारी मानकों पर लौटना चाहते हैं?";

    if (confirm(confirmMsg)) {
      localStorage.removeItem("police_planner_sectors");
      localStorage.removeItem("police_planner_strategies");
      
      const client = getSupabaseClient();
      if (client) {
        try {
          await client.from("sectors_state").delete().neq("id", 0);
          await client.from("ai_strategies").delete().neq("id", 0);
        } catch (err) {
          console.error("Supabase reset delete error:", err);
        }
      }

      const localizedData = language === 'en' ? PRIORITY_SECTORS_EN : PRIORITY_SECTORS_HI;
      setSectors(localizedData);
      setGeneratedStrategies({});
      setActiveSectorId(1);
      setViewMode("dashboard");
    }
  };

  // Safe printing layout trigger
  const handlePrintTrigger = () => {
    window.print();
  };

  // Calculating Overall state index percentages (across all 10 modules / 50 tasks)
  const calculateOverallProgress = () => {
    if (sectors.length === 0) return 0;
    
    let totalActions = 0;
    let completedActions = 0;

    sectors.forEach((sec) => {
      totalActions += sec.defaultActions.length;
      completedActions += sec.defaultActions.filter(a => a.completed).length;
    });

    return totalActions > 0 ? Math.round((completedActions / totalActions) * 100) : 0;
  };

  const overallProgress = calculateOverallProgress();
  const activeSector = sectors.find(sec => sec.id === activeSectorId) || sectors[0];

  return (
    <div className="min-h-screen bg-transparent text-slate-900 flex flex-col font-sans subpixel-antialiased">
      
      {/* HEADER BAR */}
      <Header 
        overallProgress={overallProgress}
        viewMode={viewMode}
        setViewMode={setViewMode}
        onPrint={handlePrintTrigger}
        onReset={handleResetAll}
        isSupabaseConnected={isSupabaseConnected}
      />

      {/* WORKSPACE WRAPPER */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 space-y-6">
        
        {/* VIEW A: TRADITIONAL INTERACTIVE DASHBOARD PANEL */}
        {viewMode === "dashboard" && sectors.length > 0 && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
              
              {/* LEFT PROFILE SIDEBAR: SECTOR MENU (10 POINT GRID) */}
              <div className="lg:col-span-4 h-full">
                <PriorityList 
                  sectors={sectors}
                  activeId={activeSectorId}
                  onSelectSector={(id) => setActiveSectorId(id)}
                />
              </div>

              {/* MIDDLE COCKPIT: OPERATIONAL BOARD FOR SELECTED POINT */}
              <div className="lg:col-span-8 h-full">
                <ActiveSectorView 
                  sector={activeSector}
                  onToggleAction={handleToggleAction}
                  onAddCustomAction={handleAddCustomAction}
                  onDeleteAction={handleDeleteAction}
                  onEditAction={handleEditAction}
                  generatedStrategies={generatedStrategies}
                  onSaveStrategy={handleSaveStrategy}
                />
              </div>

            </div>
            
            {/* NOTIFICATION HISTORY - Now visible right on the dashboard! */}
            <div className="mt-8">
              <NotificationHistoryView />
            </div>
          </div>
        )}

        {/* VIEW B: FULL GOVERNMENT COMPREHENSIVE STATUS REPORT OVERLOOK */}
        {viewMode === "report" && sectors.length > 0 && (
          <OverviewReport 
            sectors={sectors}
            onSelectSector={(id) => {
              setActiveSectorId(id);
              setViewMode("dashboard");
            }}
            overallProgress={overallProgress}
          />
        )}
      </main>

      {/* FOOTER BAR */}
      <footer className="bg-white/60 border-t border-slate-200 py-6 text-center select-none text-xs text-slate-500 max-w-none w-full print:hidden backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-4 space-y-2.5">
          <div className="flex items-center justify-center gap-1.5 text-indigo-600 font-semibold uppercase tracking-wider">
            <Landmark className="w-4 h-4" />
            <span>{language === 'en' ? "National Law & Order and Security Database System" : "राष्ट्रीय कानून व्यवस्था और सुरक्षा डेटाबेस प्रणाली"}</span>
          </div>
          <p className="leading-relaxed text-slate-600 max-w-md mx-auto text-xs">
            {language === 'en' 
              ? "This system is authorized to align security mechanism strengthening, human rights protection, and impartial legal investigations completely online and in a transparent planned format."
              : "यह प्रणाली सुरक्षा तंत्र के सुदृढ़ीकरण, मानवाधिकारों के संरक्षण, और निष्पक्ष कानूनी विवेचनाओं को पूर्णतः ऑनलाइन एवं पारदर्शी योजनाबद्ध प्रारूप में संरेखित करने के लिए अधिकृत है।"}
          </p>
          <p className="text-[10px] text-slate-500">
            © 2026 {language === 'en' ? "Intelligent Police Planning Console. National Security Guidelines Enhancement." : "इंटेलिजेंट पुलिस प्लानिंग कंसोल। राष्ट्रीय सुरक्षा मार्गदर्शिका संवर्धन।"} All Rights Reserved.
          </p>
        </div>
      </footer>

      {/* 🖨️ SPECIALIZED OFF-THE-GRID STYLED PRINTABLE REPORT CONTAINER (HIDDEN VIA CSS EXCEPT DURING PRINT WINDOW) */}
      <div className="hidden print:block print:bg-white print:text-black p-8 space-y-8 absolute inset-0 text-slate-900 leading-normal select-text">
        <center className="space-y-3 pb-6 border-b-4 border-slate-200">
          <h1 className="text-3xl font-black uppercase tracking-tight text-slate-900 font-serif">
            {language === 'en' ? "National Police Administrative Service" : "राष्ट्रीय पुलिस प्रशासनिक सेवा"}
          </h1>
          <h2 className="text-xl font-bold bg-white text-slate-900 px-4 py-1.5 rounded inline-block">
            {language === 'en' ? "10-Point Smart Policing Master Action Plan (Official Action SOP Dossier)" : "10-सूत्रीय स्मार्ट पुलिसिंग मास्टर कार्ययोजना (Official Action SOP Dossier)"}
          </h2>
          <p className="text-xs text-slate-600 font-semibold tracking-wider">
            {language === 'en' ? "Print Date:" : "मुद्रण तिथि:"} {new Date().toLocaleDateString(language === 'en' ? "en-US" : "hi-IN")} | {language === 'en' ? "Overall National Action Execution Index:" : "समग्र राष्ट्रीय कार्य संपादन सूचकांस्क:"} {overallProgress}% ({language === 'en' ? "Rating:" : "रेटिंग:"} {overallProgress >= 75 ? "A+" : "B"})
          </p>
        </center>

        <div className="space-y-8 pt-6">
          {sectors.map((sec) => {
            const completed = sec.defaultActions.filter(a => a.completed);
            const pending = sec.defaultActions.filter(a => !a.completed);

            return (
              <div key={sec.id} className="page-break-inside-avoid space-y-3 pb-6 border-b border-gray-300">
                <h3 className="text-lg font-extrabold text-slate-900 font-sans">
                  {language === 'en' ? "Priority" : "प्राथमिकता"} #{sec.id}: {sec.title}
                </h3>
                <p className="text-sm italic text-gray-700 font-medium">Objective: {sec.objective}</p>

                {/* Subtasks listing */}
                <div className="space-y-1.5 pl-3">
                  <h4 className="text-xs uppercase font-extrabold text-slate-800 tracking-wider">
                    {language === 'en' ? "Action Status:" : "कार्रवाई स्थिति:"}
                  </h4>
                  <ul className="list-disc pl-4 text-xs space-y-1">
                    {completed.map(act => (
                      <li key={act.id} className="text-green-800">
                        <strong>[✔️ {language === 'en' ? "Completed" : "पूर्ण"}] {act.title}</strong> - {act.description} ({language === 'en' ? "Nodal:" : "नोडल:"} {act.owner})
                      </li>
                    ))}
                    {pending.map(act => (
                      <li key={act.id} className="text-gray-600">
                        <strong>[❌ {language === 'en' ? "Incomplete" : "अपूर्ण"}] {act.title}</strong> - {act.description} ({language === 'en' ? "Est. Time:" : "अनुमानित समय:"} {act.timeline}, {language === 'en' ? "Nodal:" : "नोडल:"} {act.owner})
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>

        <div className="pt-16 flex justify-between text-xs font-bold text-slate-700">
          <div>
            __________________________<br />
            {language === 'en' ? "Reviewing Officer's Signature" : "समीक्षक अधिकारी के हस्ताक्षर"}
          </div>
          <div>
            __________________________<br />
            {language === 'en' ? "Director/DG Signature" : "निदेशक/महानिदेशक सिग्नेचर"}
          </div>
        </div>
      </div>

    </div>
  );
}
