import React, { useState, useEffect } from "react";
import { PRIORITY_SECTORS, PrioritySector, ActionStep } from "./data";
import { Header } from "./components/Header";
import { PriorityList } from "./components/PriorityList";
import { ActiveSectorView } from "./components/ActiveSectorView";
import { OverviewReport } from "./components/OverviewReport";
import { 
  Building2, Award, Landmark, CheckSquare, Sparkles, Scale, Info, 
  HelpCircle, ChevronRight, FileText, CheckCircle
} from "lucide-react";
import { getSupabaseClient, saveSupabaseConfig } from "./lib/supabase";

export default function App() {
  // Global Sector state (restored from localStorage if possible)
  const [sectors, setSectors] = useState<PrioritySector[]>([]);
  const [activeSectorId, setActiveSectorId] = useState<number>(1);
  const [viewMode, setViewMode] = useState<"dashboard" | "report">("dashboard");
  
  // Storage of all custom AI strategies generated by Gemini
  const [generatedStrategies, setGeneratedStrategies] = useState<{ [key: string]: string }>({});

  const [isSupabaseConnected, setIsSupabaseConnected] = useState(false);

  // Initialize and load state
  useEffect(() => {
    const savedSectors = localStorage.getItem("police_planner_sectors");
    const savedStrategies = localStorage.getItem("police_planner_strategies");

    if (savedSectors) {
      try {
        setSectors(JSON.parse(savedSectors));
      } catch (e) {
        setSectors(PRIORITY_SECTORS);
      }
    } else {
      setSectors(PRIORITY_SECTORS);
    }

    if (savedStrategies) {
      try {
        setGeneratedStrategies(JSON.parse(savedStrategies));
      } catch (e) {
        setGeneratedStrategies({});
      }
    }

    // Check if Supabase client config exists
    const client = getSupabaseClient();
    setIsSupabaseConnected(!!client);
  }, []);

  // Fetch data from Supabase if connected
  const loadDataFromSupabase = async () => {
    const client = getSupabaseClient();
    if (!client) return;

    try {
      // 1. Fetch sectors checklist state
      const { data: dbSectors, error: sectorsError } = await client
        .from("sectors_state")
        .select("*");

      if (!sectorsError && dbSectors && dbSectors.length > 0) {
        setSectors(prev => {
          return prev.map(sec => {
            const matched = dbSectors.find((d: any) => d.sector_id === sec.id);
            if (matched) {
              return {
                ...sec,
                defaultActions: matched.default_actions
              };
            }
            return sec;
          });
        });
      }

      // 2. Fetch AI strategies
      const { data: dbStrategies, error: strategiesError } = await client
        .from("ai_strategies")
        .select("*");

      if (!strategiesError && dbStrategies && dbStrategies.length > 0) {
        const mapped: { [key: string]: string } = {};
        dbStrategies.forEach((item: any) => {
          mapped[item.strategy_key] = item.content;
        });
        setGeneratedStrategies(prev => ({
          ...prev,
          ...mapped
        }));
      }
    } catch (err) {
      console.error("Supabase sync fetch error:", err);
    }
  };

  useEffect(() => {
    if (isSupabaseConnected) {
      loadDataFromSupabase();
    }
  }, [isSupabaseConnected]);

  // Save changes to localStorage & Supabase
  const saveSectorsState = async (updatedSectors: PrioritySector[]) => {
    setSectors(updatedSectors);
    localStorage.setItem("police_planner_sectors", JSON.stringify(updatedSectors));

    const client = getSupabaseClient();
    if (client) {
      try {
        for (const sec of updatedSectors) {
          await client
            .from("sectors_state")
            .upsert({
              sector_id: sec.id,
              default_actions: sec.defaultActions,
              updated_at: new Date().toISOString()
            }, { onConflict: "sector_id" });
        }
      } catch (err) {
        console.error("Supabase save error:", err);
      }
    }
  };

  // Toggle SOP Action task status
  const handleToggleAction = (sectorId: number, actionId: string) => {
    const updated = sectors.map((sec) => {
      if (sec.id === sectorId) {
        return {
          ...sec,
          defaultActions: sec.defaultActions.map((act) => {
            if (act.id === actionId) {
              return { ...act, completed: !act.completed };
            }
            return act;
          })
        };
      }
      return sec;
    });

    saveSectorsState(updated);
  };

  // Append new custom actions to checklists
  const handleAddCustomAction = (
    sectorId: number,
    title: string,
    description: string,
    timeline: string,
    owner: string,
    ownerPhone?: string,
    ownerEmail?: string
  ) => {
    const newAction: ActionStep = {
      id: `${sectorId}_custom_${Date.now()}`,
      title,
      description,
      timeline,
      owner,
      ownerPhone,
      ownerEmail,
      completed: false,
      isCustom: true
    };

    const updated = sectors.map((sec) => {
      if (sec.id === sectorId) {
        return {
          ...sec,
          defaultActions: [...sec.defaultActions, newAction]
        };
      }
      return sec;
    });

    saveSectorsState(updated);
  };

  // Delete an action from checklist (custom or default)
  const handleDeleteAction = (sectorId: number, actionId: string) => {
    const updated = sectors.map((sec) => {
      if (sec.id === sectorId) {
        return {
          ...sec,
          defaultActions: sec.defaultActions.filter((act) => act.id !== actionId)
        };
      }
      return sec;
    });

    saveSectorsState(updated);
  };

  // Edit fields of an existing action element
  const handleEditAction = (sectorId: number, actionId: string, updatedFields: Partial<ActionStep>) => {
    const updated = sectors.map((sec) => {
      if (sec.id === sectorId) {
        return {
          ...sec,
          defaultActions: sec.defaultActions.map((act) => {
            if (act.id === actionId) {
              return { ...act, ...updatedFields };
            }
            return act;
          })
        };
      }
      return sec;
    });

    saveSectorsState(updated);
  };

  // Save generated strategy
  const handleSaveStrategy = async (sectorId: number, scenarioKey: string, text: string) => {
    const updated = {
      ...generatedStrategies,
      [scenarioKey]: text
    };
    setGeneratedStrategies(updated);
    localStorage.setItem("police_planner_strategies", JSON.stringify(updated));

    const client = getSupabaseClient();
    if (client) {
      try {
        await client
          .from("ai_strategies")
          .upsert({
            strategy_key: scenarioKey,
            content: text,
            updated_at: new Date().toISOString()
          }, { onConflict: "strategy_key" });
      } catch (err) {
        console.error("Supabase strategy sync error:", err);
      }
    }
  };

  // Reset entire application to official defaults
  const handleResetAll = async () => {
    if (confirm("क्या आप वाकई सभी कस्टमाइजेशन, सब-टास्क और जनरेट की गई AI रणनीतियों को रीसेट कर सरकारी मानकों पर लौटना चाहते हैं?")) {
      localStorage.removeItem("police_planner_sectors");
      localStorage.removeItem("police_planner_strategies");
      
      const client = getSupabaseClient();
      if (client) {
        try {
          await client.from("sectors_state").delete().neq("id", 0);
          await client.from("ai_strategies").delete().neq("id", 0);
        } catch (err) {
          console.error("Supabase reset delete error:", err);
        }
      }

      setSectors(PRIORITY_SECTORS);
      setGeneratedStrategies({});
      setActiveSectorId(1);
      setViewMode("dashboard");
    }
  };

  const handleSupabaseConfigChange = (url: string, key: string) => {
    saveSupabaseConfig(url, key);
    const client = getSupabaseClient();
    setIsSupabaseConnected(!!client);
    if (client) {
      loadDataFromSupabase();
    } else {
      // Reload from local storage fallback
      const savedSectors = localStorage.getItem("police_planner_sectors");
      const savedStrategies = localStorage.getItem("police_planner_strategies");
      if (savedSectors) setSectors(JSON.parse(savedSectors));
      if (savedStrategies) setGeneratedStrategies(JSON.parse(savedStrategies));
    }
  };

  // Safe printing layout trigger
  const handlePrintTrigger = () => {
    window.print();
  };

  // Calculating Overall state index percentages (across all 10 modules / 50 tasks)
  const calculateOverallProgress = () => {
    if (sectors.length === 0) return 0;
    
    let totalActions = 0;
    let completedActions = 0;

    sectors.forEach((sec) => {
      totalActions += sec.defaultActions.length;
      completedActions += sec.defaultActions.filter(a => a.completed).length;
    });

    return totalActions > 0 ? Math.round((completedActions / totalActions) * 100) : 0;
  };

  const overallProgress = calculateOverallProgress();
  const activeSector = sectors.find(sec => sec.id === activeSectorId) || sectors[0];

  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-800 flex flex-col font-sans subpixel-antialiased selection:bg-amber-500/25 selection:text-amber-900">
      
      {/* HEADER BAR */}
      <Header 
        overallProgress={overallProgress}
        viewMode={viewMode}
        setViewMode={setViewMode}
        onPrint={handlePrintTrigger}
        onReset={handleResetAll}
        isSupabaseConnected={isSupabaseConnected}
        onSupabaseConfigChange={handleSupabaseConfigChange}
      />


      {/* WORKSPACE WRAPPER */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 space-y-6">
        
        {/* VIEW A: TRADITIONAL INTERACTIVE DASHBOARD PANEL */}
        {viewMode === "dashboard" && sectors.length > 0 && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
            
            {/* LEFT PROFILE SIDEBAR: SECTOR MENU (10 POINT GRID) */}
            <div className="lg:col-span-4 h-full">
              <PriorityList 
                sectors={sectors}
                activeId={activeSectorId}
                onSelectSector={(id) => setActiveSectorId(id)}
              />
            </div>

            {/* MIDDLE COCKPIT: OPERATIONAL BOARD FOR SELECTED POINT */}
            <div className="lg:col-span-8 h-full">
              <ActiveSectorView 
                sector={activeSector}
                onToggleAction={handleToggleAction}
                onAddCustomAction={handleAddCustomAction}
                onDeleteAction={handleDeleteAction}
                onEditAction={handleEditAction}
                generatedStrategies={generatedStrategies}
                onSaveStrategy={handleSaveStrategy}
              />
            </div>

          </div>
        )}

        {/* VIEW B: FULL GOVERNMENT COMPREHENSIVE STATUS REPORT OVERLOOK */}
        {viewMode === "report" && sectors.length > 0 && (
          <OverviewReport 
            sectors={sectors}
            onSelectSector={(id) => {
              setActiveSectorId(id);
              setViewMode("dashboard");
            }}
            overallProgress={overallProgress}
          />
        )}
      </main>

      {/* FOOTER BAR */}
      <footer className="bg-white border-t border-slate-200/80 py-6 text-center select-none text-xs text-slate-500 max-w-none w-full print:hidden">
        <div className="max-w-7xl mx-auto px-4 space-y-2.5">
          <div className="flex items-center justify-center gap-1.5 text-amber-600 font-semibold uppercase tracking-wider">
            <Landmark className="w-4 h-4" />
            <span>राष्ट्रीय कानून व्यवस्था और सुरक्षा डेटाबेस प्रणाली</span>
          </div>
          <p className="leading-relaxed text-slate-550 max-w-md mx-auto text-xs">
            यह प्रणाली सुरक्षा तंत्र के सुदृढ़ीकरण, मानवाधिकारों के संरक्षण, और निष्पक्ष कानूनी विवेचनाओं को पूर्णतः ऑनलाइन एवं पारदर्शी योजनाबद्ध प्रारूप में संरेखित करने के लिए अधिकृत है।
          </p>
          <p className="text-[10px] text-slate-400">
            © 2026 इंटेलिजेंट पुलिस प्लानिंग कंसोल। राष्ट्रीय सुरक्षा मार्गदर्शिका संवर्धन। All Rights Reserved.
          </p>
        </div>
      </footer>

      {/* 🖨️ SPECIALIZED OFF-THE-GRID STYLED PRINTABLE REPORT CONTAINER (HIDDEN VIA CSS EXCEPT DURING PRINT WINDOW) */}
      <div className="hidden print:block print:bg-white print:text-black p-8 space-y-8 absolute inset-0 text-slate-900 leading-normal select-text">
        <center className="space-y-3 pb-6 border-b-4 border-slate-900">
          <h1 className="text-3xl font-black uppercase tracking-tight text-slate-900 font-serif">
            राष्ट्रीय पुलिस प्रशासनिक सेवा
          </h1>
          <h2 className="text-xl font-bold bg-slate-900 text-white px-4 py-1.5 rounded inline-block">
            10-सूत्रीय स्मार्ट पुलिसिंग मास्टर कार्ययोजना (Official Action SOP Dossier)
          </h2>
          <p className="text-xs text-slate-600 font-semibold tracking-wider">
            मुद्रण तिथि: {new Date().toLocaleDateString("hi-IN")} | समग्र राष्ट्रीय कार्य संपादन सूचकांस्क: {overallProgress}% (रेटिंग: {overallProgress >= 75 ? "A+" : "B"})
          </p>
        </center>

        <div className="space-y-8 pt-6">
          {sectors.map((sec) => {
            const completed = sec.defaultActions.filter(a => a.completed);
            const pending = sec.defaultActions.filter(a => !a.completed);

            return (
              <div key={sec.id} className="page-break-inside-avoid space-y-3 pb-6 border-b border-gray-300">
                <h3 className="text-lg font-extrabold text-slate-900 font-sans">
                  प्राथमिकता #{sec.id}: {sec.title}
                </h3>
                <p className="text-sm italic text-gray-700 font-medium">Objective: {sec.objective}</p>

                {/* Subtasks listing */}
                <div className="space-y-1.5 pl-3">
                  <h4 className="text-xs uppercase font-extrabold text-slate-800 tracking-wider">कार्रवाई स्थिति:</h4>
                  <ul className="list-disc pl-4 text-xs space-y-1">
                    {completed.map(act => (
                      <li key={act.id} className="text-green-800">
                        <strong>[✔️ पूर्ण] {act.title}</strong> - {act.description} (नोडल: {act.owner})
                      </li>
                    ))}
                    {pending.map(act => (
                      <li key={act.id} className="text-gray-600">
                        <strong>[❌ अपूर्ण] {act.title}</strong> - {act.description} (अनुमानित समय: {act.timeline}, नोडल: {act.owner})
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>

        <div className="pt-16 flex justify-between text-xs font-bold text-slate-700">
          <div>
            __________________________<br />
            समीक्षक अधिकारी के हस्ताक्षर
          </div>
          <div>
            __________________________<br />
            निदेशक/महानिदेशक सिग्नेचर
          </div>
        </div>
      </div>

    </div>
  );
}
